#Lists, Tuples, Dictionaries and Sets in Python
###By Noe Lozano Mendoza

Python has different types of arrays to store our data in different ways. These are lists, tuples, dictionaries and arrays. 

First we will get to know lists.
Lists are the type of array that most programmers are most familiar with, since it is an array that is based on data stored in each index of a created list.

The list is created as follows:


```
data = []
```
As simple as giving it a name and assigning square brackets. With this python already recognizes that a list called "data" has been created.

Now, to add data we will do the following:


```
data = [1, 2, 3, 4, 5]
```
The data must be separated by commas to occupy an array index and can have any type of data in it, not just numbers. For example:



```
names = ['Pepe','Juan','Maria','Rodrigo','Santiago']
bools = [True, False]
```



However... What are the indexes?

Basically they are the memory spaces where the data is stored, starting from 0. In the previous example it would look like this.


```
[1,2,3,4,5] are found in data[0, 1, 2, 3, 4]
```
so that


```
data[0] = 1, data[1] = 2, data[2] = 3, ...
```
It is important to know about indexes to understand how python arrays work, however, some python arrays don't need it, or work differently.

Now let's try some examples:

Let's declare a list of five numbers:

In [1]:
numbers = [1,2,3,4,5]

In [2]:
#According to what we learned about indexes, we can handle each data individually and perform operations between them.

sum = numbers[0] + numbers[1] + numbers[2] + numbers[3] + numbers[4]
substract = numbers[0] - numbers[1] - numbers[2] - numbers[3] - numbers[4]
multiplication = numbers[0] * numbers[1] * numbers[2] * numbers[3] * numbers[4]
division = numbers[0] / numbers[1] / numbers[2] / numbers[3] / numbers[4]

print(sum)
print(substract)
print(multiplication)
print(division)

15
-13
120
0.008333333333333333

In [3]:
#We can also assign new values to them
numbers[0] = 5
numbers

[5, 2, 3, 4, 5]

In [4]:
#And of any type
numbers[0] = 'Camaron'
numbers

['Camaron', 2, 3, 4, 5]

###Broadly speaking, that's what lists are. And although you can do a lot of things with them. There are other types of arrangements that can be even more interesting.

For example... 
##The tuples.

Tuples work and have almost the same properties as lists, they have indexes and you can store anything in them. 

However, their 2 biggest differences are:


*   How they are declared:


```
#The tuples are declared with parentheses instead of square brackets.

data = ()
```


*   Immutable: This means that its elements cannot be replaced or modified. To demonstrate this let's do a test.

Let's declare a tuple of five numbers:

In [5]:
num_tuple = (1,2,3,4,5)
word_tuple = ('Pepe', 'Tania', 'Alfonso')

In [6]:
word_tuple[1]

'Tania'

In [7]:
num_tuple[0] = 5

TypeError: ignored

As you can see in the previous example, the content inside the tuple cannot be modified, so it is a great tool to store information and avoid errors because they cannot be modified.

#Dictionaries
Dictionaries, unlike lists and tuples, work with "keys" or identifiers and their respective values. It is a great way to store data that we consider that needs a relation, but we don't want to use a new variable or a whole list for a specific data. 

Dictionaries are declared with keys **AND** with at least one key and value relationship. For example:


```
clients = {'name' : 'Benito', 'lastname' : 'Juarez', 'age' : 45, 'married' : True}
```
As we can see we have identifiers, or keys, that contain a value. 

The data in a dictionary is called in several ways. Let's see it directly with the example above:

In [8]:
#Let us first declare the dictionary
clients = {'name' : 'Benito', 'lastname' : 'Juarez', 'age' : 45, 'married' : True}
clients

{'name': 'Benito', 'lastname': 'Juarez', 'age': 45, 'married': True}

In [9]:
#Let's see how the value of each dictionary key is called.
print(clients['name'])
print(clients['lastname'])
print(clients['age'])
print(clients['married'])

Benito
Juarez
45
True

In [10]:
print(clients['name'] + ' ' + clients['lastname'])

Benito Juarez

And finally...
##Sets

Sets have the same visualization as lists (they are also mutable) and tuples. They only have 4 major differences.


* They are disorganized
* You can't call data with indexes
* You cannot have repeated data
* They have operations that serve in the same way as the mathematical sets (union, intersection. for example).

They are declared with braces:


```
set = {}
```
And we can enter data in the same way as the list and the tuple.

```
set = {1, 2, 3,'Pablo', False}
```
Let see now some examples to demonstrate its main characteristics:

In [11]:
#Let's declare 2 sets
num = {1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
letras = {'a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e', 'f', 'g'}

In [12]:
#Now let's see how they are visualize
print(num)
print(letras)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
{'c', 'f', 'e', 'g', 'b', 'a', 'd'}

As we can see, the set of letters is completely disorganized, in neither of the 2 there are repeated elements and it is not possible to extract data. However we can do interesting operations such as the union of sets and their intersections. (Although it is not bad to mention that all kinds of logical operators can be used)

In [14]:
#Let's declare one more set
num2 = {11,12,13,14,5,6,8,14,15,16,4,2,1,1,17,18,19,3,4,5,6,20}
num2

{1, 2, 3, 4, 5, 6, 8, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}

In [15]:
#Now we will use the operands & and | for intersection and union respectively
print(num & num2)
print(num | num2)

{1, 2, 3, 4, 5, 6, 8}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20}